### ISSUE TITLE
Fix Maven build

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/openfire-jmxweb-plugin#1]
To build plugins for Openfire 4.3.0 pom.xml should include repositories tags pointing to Archiva. If plugin has pages in Admin Console, web.xml should also be added.

For references:
https://github.com/igniterealtime/openfire-clientControl-plugin/pull/11

**Comment by deleolajide** [comment]
Started working on this. Need to spend more time tidying up the documentation before a proper Archiva release. In the meantime, an interim release is available from https://github.com/igniterealtime/openfire-jmxweb-plugin/releases/tag/v0.0.9

**Comment by guusdk** [comment]
I'm thinking that all the work that typically goes into a 'fix maven build' issue has been done in https://github.com/igniterealtime/openfire-jmxweb-plugin/commit/465eb8a69db3dc2bdd68dbe33193b1839bdc78cf

Do we need to keep this issue open?

**Comment by guusdk** [comment]
(I'll take that as a 'no' - feel free to re-open)
