### ISSUE TITLE
404 on http://your-server:7070/hawtio

### ISSUE THREAD

**Issue by evle-zzz** [igniterealtime/openfire-jmxweb-plugin#2]
After installation and initial configuration (with xmpp.jmx.enabled=true, xmpp.jmx.secure=false)
http://your-server:7070/hawtio and http://your-server:7070/jolokia return error 

> HTTP ERROR 404
> Problem accessing /hawtio/. Reason:
>     Not Found
> Powered by Jetty:// 9.4.18.v20190429

Openfire 4.4.1, JmxWeb Plugin 0.0.7 (from plugins page in openfire)

**Comment by Hagabard** [comment]
I ran into the same problem on 4.2 and even after an upgrade to 4.3 it was still not working.  I haven't attempted updating it to 4.4 yet, but looks like I will still have no luck.  How can I help troubleshoot?  Would be really nice to get jmx going for insight/metrics/graphing.

**Comment by deleolajide** [comment]
I will take a look. Not used it in a while

**Comment by GregDThomas** [comment]
At around Openfire 4.2 the API for adding servlet contexts to the port 7070 tomcat changed; the plugin probably needs an update to reflect that.

**Comment by deleolajide** [comment]
> At around Openfire 4.2 the API for adding servlet contexts to the port 7070 tomcat changed; the plugin probably needs an update to reflect that.

I remember making that change :-)
https://github.com/igniterealtime/openfire-jmxweb-plugin/blob/713e74465ebccdcd53535f8ab19ed9aebf4c58d2/src/java/com/ifsoft/jmxweb/plugin/JmxWebPlugin.java#L142

**Comment by deleolajide** [comment]
I got it working.

http://desktop-545pc5b:7070/jolokia/ produced

```
{
    "request":{"type":"version"},
    "value":{
        "agent":"1.3.3",
        "protocol":"7.2",
        "config":{
            "maxCollectionSize":"1000",
            "agentId":"10.0.75.1-19632-6db00a71-servlet",
            "debug":"false",
            "agentType":"servlet",
            "serializeException":"false",
            "detectorOptions":"{}",
            "dispatcherClasses":"org.jolokia.jsr160.Jsr160RequestDispatcher",
            "maxDepth":"15",
            "discoveryEnabled":"false",
            "canonicalNaming":"true",
            "historyMaxEntries":"10",
            "includeStackTrace":"true",
            "maxObjects":"0",
            "debugMaxEntries":"100"
        },"info":{
            "product":"jetty",
            "vendor":"Eclipse",
            "version":"9.4.18.v20190429"
        }
    },
    "timestamp":1574792908,
    "status":200
}
```

**Comment by deleolajide** [comment]
Dashboard is also working from http://desktop-545pc5b:7070/hawtio/

![image](https://user-images.githubusercontent.com/110731/69662079-98467e80-107b-11ea-8599-430fd8d1583c.png)

**Comment by Hagabard** [comment]
Seems to work here now as well.  Thanks for the quick response!

**Comment by guusdk** [comment]
Fixed in https://github.com/igniterealtime/openfire-jmxweb-plugin/commit/465eb8a69db3dc2bdd68dbe33193b1839bdc78cf
