### ISSUE TITLE
Core Client Threadpool MBean registration fails when server is restarted

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/openfire-jmxweb-plugin#9]
When this plugin is installed in a server, and that server gets restarted, the registration of the MBean that is used to monitor the 'core client threadpool' always fails.

This registration is done when the plugin initializes, and requires the socket acceptor associated to those client connections. Acceptors are started only after all plugins have started.

**Comment by GregDThomas** [comment]
Would something simpler suffice? e.g. https://github.com/igniterealtime/openfire-hazelcast-plugin/blob/master/src/java/org/jivesoftware/openfire/plugin/HazelcastPlugin.java#L48

**Comment by guusdk** [comment]
I don't think so, at least not reliably, as that is the exact same construct used for the thing that we're waiting on (the socket acceptors) to start initialization. I don't think we can reliably tell which one will come first.
